#!/bin/bash


# env vars used on all tests

export MESSAGE_PATH_LIST=(
  "/inputs/lorem-1k.txt"
  "/inputs/lorem-10k.txt"
  "/inputs/lorem-100k.txt"
  "/inputs/lorem-1M.txt"
  "/inputs/lorem-10M.txt"
  "/inputs/lorem-100M.txt"
)
export N_MESSAGES_LIST=(10 100 300 500 700 1000)
export MESSAGE_MANY_TESTS="/inputs/lorem-100k.txt"

mkdir -p output_bench

# bench memory
## remove comented lines for bench_mem
sed -i '/HACK: bench_mem/ s/^#//' main.py 

## with different messages

export N_MESSAGES=1
for MESSAGE_PATH in ${MESSAGE_PATH_LIST[@]}
do
  export MESSAGE_PATH
  python3 main.py
done

## with diferent number of signatures/verifies

export MESSAGE_PATH=$MESSAGE_MANY_TESTS
for N_MESSAGES in ${N_MESSAGES_LIST[@]}
do
  export N_MESSAGES
  python3 main.py
done


## coment lines for bench_mem
sed -i '/HACK: bench_mem/ s/^/#/' main.py 

# move all files generated by python bench mem to folder bench_mem
mkdir -p bench_mem
mv bench-mem*.csv bench_mem
mv bench_mem output_bench

# bench cpu

## with different messages
export N_MESSAGES=1
for MESSAGE_PATH in ${MESSAGE_PATH_LIST[@]}
do
  export MESSAGE_PATH
  INPUT_NAME=$(basename $MESSAGE_PATH .txt)
  OUTPUT_NAME="bench-cpu-${INPUT_NAME}-${N_MESSAGES}.prof"
  python3 -m cProfile -o $OUTPUT_NAME main.py
done

## with different messages

export MESSAGE_PATH=$MESSAGE_MANY_TESTS
for N_MESSAGES in ${N_MESSAGES_LIST[@]}
do
  export N_MESSAGES
  INPUT_NAME=$(basename $MESSAGE_PATH .txt)
  OUTPUT_NAME="bench-cpu-${INPUT_NAME}-${N_MESSAGES}.prof"
  python3 -m cProfile -o $OUTPUT_NAME main.py
done

# move all files generated by profiling main.py to bench_cpu
mkdir -p bench_cpu
mv bench-cpu*.prof bench_cpu
mv bench_cpu output_bench
