#!/bin/bash

# bench memory
## remove comented lines for bench_mem
sed -i '/HACK: bench_mem/ s/^#//' main.py 

## with different messages

export N_MESSAGES=1
export MESSAGE_PATH_LIST=(
  "../../inputs/lorem-1k.txt"
  "../../inputs/lorem-10k.txt"
  "../../inputs/lorem-100k.txt"
  "../../inputs/lorem-1M.txt"
  "../../inputs/lorem-10M.txt"
  "../../inputs/lorem-100M.txt"
)
for MESSAGE_PATH in ${MESSAGE_PATH_LIST[@]}
do
  export MESSAGE_PATH
  python3 main.py
done

## with diferent number of signatures/verifies

export N_MESSAGES_LIST=(10 100 1000)
export MESSAGE_PATH="../../inputs/lorem-100k.txt"
for N_MESSAGES in ${N_MESSAGES_LIST[@]}
do
  export N_MESSAGES
  python3 main.py
done


## coment lines for bench_mem
sed -i '/HACK: bench_mem/ s/^/#/' main.py 

# move all files generated by python bench mem to folder bench_mem
mkdir -p bench_mem
mv bench-mem*.csv bench_mem
